### ISSUE TITLE
comicDesc variable not being read

### ISSUE THREAD

**Issue by Nicolejeanne** [YenPingLiu/Agents-of-APIs#20]
@YenPingLiu I was skimming the JS and noticed that the comicDesc variable is showing that it's not being read anywhere. Is there a reason you didn't want to include that information on the cards or does it just still need to be added?

**Comment by YenPingLiu** [comment]
@Nicolejeanne I thought that using the description might make each comic card too long, so I decided not to include it. Let me do some tests to see how it actually looks.
